env:
  global:
    - CONAN_USERNAME: "helmesjo"
    - CONAN_LOGIN_USERNAME: "helmesjo"
    - CONAN_CHANNEL: "stable" # because of bug in conan-package-tools, we always upload packages as stable
    - CONAN_UPLOAD: "https://api.bintray.com/conan/helmesjo/public-conan"
    - CONAN_REMOTES: "https://api.bintray.com/conan/helmesjo/public-conan,https://api.bintray.com/conan/bincrafters/public-conan"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 0

linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
     - <<: *linux
       env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86_64
     - <<: *linux
       env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86_64
     - <<: *linux
       env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CONAN_ARCHS=x86_64
     - <<: *linux
       env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9 CONAN_ARCHS=x86_64
     - <<: *osx
       osx_image: xcode10.1
       env: CONAN_APPLE_CLANG_VERSIONS=10.0
     - <<: *osx
       osx_image: xcode11
       env: CONAN_APPLE_CLANG_VERSIONS=11.0

install:
 - chmod +x .ci/install.sh
 - ./.ci/install.sh

script:
 - chmod +x .ci/run.sh
 - ./.ci/run.sh
